platform :ios, '14.0'

target 'ADPlayerBasicSample' do
  use_frameworks!

  pod 'AdPlayerSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'RxSwift'
           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
