platform :ios, '16.0'

target 'AdPlayerSample' do
  use_frameworks!

  pod 'AdPlayerSDK', '1.11.7'

  pod 'SwiftLint'

# uncomment the following to use RxSwift based config (iOS < 13)
#  pod 'RxSwift' # required when iOS < 13
end


# uncomment the following to use RxSwift based config (iOS < 13)
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if target.name == 'RxSwift'
#           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      end
#    end
#  end
#end
